version: '3.4'

services:
  kraevedapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:44392;http://+:80
      - ASPNETCORE_HTTPS_PORT=44392
    ports:
      - "59404:80"
      - "44392:44392"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./KraevedAPI/cert.crt:/etc/nginx/cert.crt
      - ./KraevedAPI/cert.rsa:/etc/nginx/cert.rsa
    ports:
      - "5001:44392"